### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by Mingzefei** [MatissJurevics/Gene-AI#3]
Hello,

I encountered this error after inputting my OPENAI API key and running the plugin. 
Yes, I noticed the relevant information at the bottom of the README in this project.

Could this issue be due to the absence of verified billing details? 
I am curious about it, because the API key works well in other software.

**Comment by MatissJurevics** [comment]
Hey,

From my experience, your request will be deemed unauthorised when your billing information is not verified or if your API key was disabled. I have on occasion received 401's from the api but it usually either resolves itself after some time or when you create a new key. 

Also check if your using GPT 4 for text completion or translation in settings because if you are not authorised to use it, it will also return a 401.

**Comment by Mingzefei** [comment]
I just checked again, and now it's working fine. 
It might have been a network or OpenAI issue.
Thanks!
